### ISSUE TITLE
TED subtitles

### ISSUE THREAD

**Issue by GoogleCodeExporter** [drrlramsey/xbmc-addons#65]
```
I enhanced TED talks addon with enabling subtitle on video.
The following files are modified or added from 2.2.0 version.

1. subtitleDownloader.py is added
2. settings.xml is modified to select subtitle language
3. ted_talks.py is modified to set subtitle file
4. ted_talks_scraper.py is modified to set subtitle language
5. getHTML in util.py is modified to make session cookie live over multiple 
accesses.
6. Korean language file is added

Please check the attached code and send me mail if you have any question.
```

Original issue reported on code.google.com by `hoje...@gmail.com` on 11 Oct 2010 at 11:38

Attachments:
- [plugin.video.ted.talks.zip](https://storage.googleapis.com/google-code-attachments/xbmc-addons/issue-65/comment-0/plugin.video.ted.talks.zip)

**Comment by GoogleCodeExporter** [comment]
```
Thank you! It works perfectly :)
```

Original comment by `xezpel...@gmail.com` on 11 Dec 2010 at 1:42

**Comment by GoogleCodeExporter** [comment]
Original comment by `nuka1195@gmail.com` on 30 Dec 2010 at 2:10
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
fixed settings.xml from Portugese (Brazil) and Portugese (Portugal)
to Portuguese (Brazil) and Portuguese (Portugal)

```

Original comment by `zaquieme...@gmail.com` on 1 Feb 2011 at 1:21

Attachments:
- [settings.xml](https://storage.googleapis.com/google-code-attachments/xbmc-addons/issue-65/comment-3/settings.xml)

**Comment by GoogleCodeExporter** [comment]
```
I get an error everytime I try to watch any video after I installed this plugin.
Below is what I found in the logs:

01:52:25 T:2873498480 M:2790305792  NOTICE: [PLUGIN] 'TED Talks: version 2.1.5' 
initialized!
01:52:25 T:2873498480 M:2790379520  NOTICE: [TED Talks] resources.lib.util 
attempting to open 
http://www.ted.com/talks/a_j_jacobs_year_of_living_biblically.html
01:52:25 T:2873498480 M:2790379520  NOTICE: [TED Talks] loaded cookie : <Cookie 
symfony=l84nj3uugjhhcbtb61p5gpc806 for .ted.com/>
                                            from /home/salem/.xbmc/temp/ted-cookies.lwp
01:52:27 T:2873498480 M:2789900288   ERROR: Error Type: 
exceptions.AttributeError
01:52:27 T:2873498480 M:2789900288   ERROR: Error Contents: 'NoneType' object 
has no attribute 'group'
01:52:27 T:2873498480 M:2789900288   ERROR: Traceback (most recent call last):
                                              File "/home/salem/.xbmc/addons/plugin.video.ted.talks/default.py", line 27, in ?
                                                ted_talks.Main()
                                              File "/home/salem/.xbmc/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 198, in __init__
                                                self.checkMode()
                                              File "/home/salem/.xbmc/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 256, in checkMode
                                                UI().playVideoWithSubtitle()
                                              File "/home/salem/.xbmc/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 99, in playVideoWithSubtitle
                                                video = TedTalks.getVideoDetails(self.main.args.url)
                                              File "/home/salem/.xbmc/addons/plugin.video.ted.talks/resources/lib/ted_talks_scraper.py", line 58, in getVideoDetails
                                                (id,intro) = re.search(';ti=(\d+)&introDuration=(\d+)&', html).group(1,2)
                                            AttributeError: 'NoneType' object has no attribute 'group'
01:52:27 T:3077789552 M:2789924864   ERROR: Playlist Player: skipping 
unplayable item: 0, path 
[plugin://plugin.video.ted.talks/?url=http%3A%2F%2Fwww.ted.com%2Ftalks%2Fa_j_jac
obs_year_of_living_biblically.html&mode=playVideo&name=A.J.+Jacobs%27+year+of+li
ving+biblically&icon=http%3A%2F%2Fimages.ted.com%2Fimages%2Fted%2F47395_113x85.j
pg]
01:52:27 T:3077789552 M:2789924864 WARNING: CreateFile, successfuly opened 
</home/salem/.xbmc/addons/skin.neon/720p/DialogOk.xml> instead of 
</home/salem/.xbmc/addons/skin.neon/720p/DialogOK.xml>

Don't know if it'll help, but if anyone knows how to fix it, I'll buy you a 
beer! ;)
```

Original comment by `gabriel....@gmail.com` on 26 Apr 2011 at 5:01

**Comment by GoogleCodeExporter** [comment]
```
ps: running on ubuntu 10.10
```

Original comment by `gabriel....@gmail.com` on 26 Apr 2011 at 5:11
